### ISSUE TITLE
Add (manual) AppVeyor deploy to NuGet

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#981]
I tried to use the deploy option to push the artifacts to NuGet, since we thought that was working, but nothing was found:

https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/deployment/594404

I think we need to configure the deployment as described in [Publishing to NuGet feed](https://www.appveyor.com/docs/deployment/nuget/). Although we can probably skip most of the config, maybe ending up with

```yml
deploy:
  provider: NuGet
  api_key:
    secure: m49OJ7+Jdt9an3jPcTukHA== # not the real value - we'll make one when we need it
  skip_symbols: true
```

This is tough to test. I suggest we wait 'til 3.0.0 is released and then try it out with a 3.1.0-beta.
